# Generated by Django 2.0.4 on 2018-04-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charity',
            options={'verbose_name': 'Charity', 'verbose_name_plural': 'Charities'},
        ),
        migrations.AlterField(
            model_name='charity',
            name='lat',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='charity',
            name='lng',
            field=models.SmallIntegerField(),
        ),
    ]
