# Generated by Django 2.0.4 on 2018-04-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20180407_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=13),
        ),
        migrations.AlterField(
            model_name='charity',
            name='lng',
            field=models.DecimalField(decimal_places=10, max_digits=13),
        ),
    ]
